<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>InfiniteDubhe.Engine</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../InfiniteDubhe.Core/InfiniteDubhe.Core.csproj" />
    <ProjectReference Include="../InfiniteDubhe.Platform/InfiniteDubhe.Platform.csproj" />
    <ProjectReference Include="../InfiniteDubhe.Rendering/InfiniteDubhe.Rendering.csproj" />
    <ProjectReference Include="../InfiniteDubhe.Scene/InfiniteDubhe.Scene.csproj" />
    <ProjectReference Include="../InfiniteDubhe.Input/InfiniteDubhe.Input.csproj" />
    <ProjectReference Include="../InfiniteDubhe.Resources/InfiniteDubhe.Resources.csproj" />
    <ProjectReference Include="../InfiniteDubhe.Audio/InfiniteDubhe.Audio.csproj" />
    <ProjectReference Include="../InfiniteDubhe.UI/InfiniteDubhe.UI.csproj" />
  </ItemGroup>

</Project>
