using System.Numerics;
using InfiniteDubhe.Core;

namespace InfiniteDubhe.UI;

/// <summary>
/// 下拉框：点击展开选项列表，点选一项后收起并触发 <see cref="SelectionChanged"/>。
/// 展开的选项以自动生成的子元素呈现（序列化时跳过）。列表只在本元素下方的空间内绘制与命中。
/// </summary>
public sealed class Dropdown : UIElement
{
    private readonly Text _label;
    private readonly List<Button> _optionRows = new();
    private bool _open;
    private float _fontScale = 2f;

    /// <summary>候选项文本。</summary>
    public List<string> Items { get; set; } = new();

    /// <summary>当前选中索引（越界时按 <see cref="SelectedItem"/> 读取处夹取）。</summary>
    public int SelectedIndex { get; set; }

    /// <summary>当前选中项文本（无候选项时为 null）。</summary>
    public string? SelectedItem
    {
        get
        {
            if (Items.Count == 0) return null;
            return Items[Math.Clamp(SelectedIndex, 0, Items.Count - 1)];
        }
    }

    /// <summary>常态背景色。</summary>
    public Color BackgroundColor { get; set; } = Color.FromRgb(70, 70, 96);

    /// <summary>悬停背景色。</summary>
    public Color HoverColor { get; set; } = Color.FromRgb(96, 96, 128);

    /// <summary>按压背景色。</summary>
    public Color PressedColor { get; set; } = Color.FromRgb(48, 48, 72);

    /// <summary>文本颜色。</summary>
    public Color TextColor
    {
        get => _label.Color;
        set => _label.Color = value;
    }

    /// <summary>展开箭头颜色。</summary>
    public Color ArrowColor { get; set; } = Color.White;

    /// <summary>文本缩放倍率。</summary>
    public float FontScale
    {
        get => _fontScale;
        set
        {
            _fontScale = MathF.Max(0f, value);
            _label.Scale = _fontScale;
            if (_open) RebuildOptions();
        }
    }

    /// <summary>单个选项行高度（像素）。</summary>
    public float ItemHeight { get; set; } = 28f;

    /// <summary>选中变化（参数为选中索引）。</summary>
    public event Action<Dropdown, int>? SelectionChanged;

    public Dropdown() : this(null) { }

    public Dropdown(IEnumerable<string>? items = null)
    {
        Interactable = true;
        Size = new Vector2(160f, 32f);
        _label = new Text("", _fontScale)
        {
            Anchor = new Vector2(0f, 0.5f),
            Pivot = new Vector2(0f, 0.5f),
            Position = new Vector2(10f, 0f),
        };
        _label.IsAutoGenerated = true; // 标签是自动生成的子元素，序列化时跳过（改由 Items/SelectedIndex 承载）。
        AddChild(_label);
        if (items is not null) SetItems(items);
        Clicked += _ => Toggle();
    }

    /// <summary>替换候选项（选中索引夹取到有效范围）。</summary>
    public void SetItems(IEnumerable<string> items)
    {
        ArgumentNullException.ThrowIfNull(items);
        Items.Clear();
        Items.AddRange(items);
        SelectedIndex = Items.Count > 0 ? Math.Clamp(SelectedIndex, 0, Items.Count - 1) : 0;
        if (_open) RebuildOptions();
    }

    protected override void OnSubmit(ICollection<SpriteDrawCommand> commands, ITexture white, BitmapFont? font, int layer, float depth)
    {
        _label.Content = SelectedItem ?? string.Empty;

        var saved = Color;
        Color = IsPressed ? PressedColor : IsHovered ? HoverColor : BackgroundColor;
        SubmitSolid(commands, white, layer, depth);
        Color = saved;

        // 展开箭头（内置字体 “v”）。
        if (font is not null)
        {
            var glyph = font.GetGlyph('v');
            if (!glyph.IsEmpty)
            {
                var size = new Vector2(BitmapFont.GlyphWidth * _fontScale, BitmapFont.GlyphHeight * _fontScale);
                var pos = new Vector2(
                    ComputedPosition.X + ComputedSize.X - size.X - 8f,
                    ComputedPosition.Y + (ComputedSize.Y - size.Y) * 0.5f);
                commands.Add(new SpriteDrawCommand
                {
                    Texture = font.Texture,
                    SourceRect = glyph,
                    Position = pos,
                    Rotation = 0f,
                    Origin = Vector2.Zero,
                    Scale = new Vector2(_fontScale, _fontScale),
                    Color = ArrowColor,
                    Effects = SpriteEffects.None,
                    Layer = layer,
                    LayerDepth = depth + 0.001f,
                });
            }
        }
    }

    private void Toggle()
    {
        _open = !_open;
        if (_open) RebuildOptions();
        else ClearOptions();
    }

    private void RebuildOptions()
    {
        ClearOptions();
        for (int i = 0; i < Items.Count; i++)
        {
            int index = i;
            var row = new Button(Items[i], _fontScale)
            {
                Anchor = Vector2.Zero,
                Pivot = Vector2.Zero,
                Position = new Vector2(0f, ComputedSize.Y + i * ItemHeight),
                Size = new Vector2(ComputedSize.X, ItemHeight),
            };
            row.IsAutoGenerated = true; // 选项行是运行时生成的，序列化时跳过。
            row.Clicked += _ => Select(index);
            AddChild(row);
            _optionRows.Add(row);
        }
    }

    private void ClearOptions()
    {
        foreach (var row in _optionRows) RemoveChild(row);
        _optionRows.Clear();
    }

    private void Select(int index)
    {
        _open = false;
        ClearOptions();
        SelectedIndex = index;
        SelectionChanged?.Invoke(this, index);
    }
}
