<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>InfiniteDubhe.Physics</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../InfiniteDubhe.Core/InfiniteDubhe.Core.csproj" />
    <ProjectReference Include="../InfiniteDubhe.Scene/InfiniteDubhe.Scene.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aether.Physics2D" Version="2.2.0" />
  </ItemGroup>

</Project>
